### ISSUE TITLE
New pull request

### ISSUE THREAD

**Issue by saravmajestic** [saymedia/angularjs-server#17]
Hi, Thanks for the awesome module. I just checked it out for my new project and it seems to fit very well.

I found an issue similar to https://github.com/angular-ui/ui-router/issues/50 and added a fix. Also tested with latest express and angularjs. Please check the pull request https://github.com/saymedia/angularjs-server/pull/16. Hope it will help you and others!

Thanks.

**Comment by mavin** [comment]
Thank you, any more discussion of this should happen in #16 .
