### ISSUE TITLE
Is 'eponymous' a fork?

### ISSUE THREAD

**Issue by gabrielmoreira** [saymedia/angularjs-server#21]
Is 'eponymous' a fork?
https://github.com/eponymousjs/eponymous

**Comment by apparentlymart** [comment]
It certainly seems to be. I got in touch with the author and he's updated the license file to clarify the heritage of the code.

We're not involved in the fork but I'm hopeful that some good improvements will come from it. We'll be watching for changes to incorporate back into angularjs-server.
